import { readFileSync, writeFileSync } from "fs";
import { glob } from "glob";
import { basename } from "path";
import { extractCodeBlock } from "./utils";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ImportEntry {
  notePath: string;       // relative to vault root, e.g. "060-imports/configs/.../config.yaml.md"
  sourceFile: string;     // just the filename, e.g. "config.yaml"
  sourcePath: string;     // relative source path from frontmatter title
  tags: string[];
  displayName: string;
}

export interface ImportIndex {
  byFilename: Map<string, ImportEntry[]>;
  byPathSegment: Map<string, ImportEntry[]>;
  byTag: Map<string, ImportEntry[]>;
  all: ImportEntry[];
}

export interface ChainInfo {
  path: string;
  handle: string;
  tags: string[];
  bodyText: string;
  wikilinkTargets: string[];
}

export interface ScoredMatch {
  importEntry: ImportEntry;
  score: number;
  reasons: string[];
}

export interface ChainLinkerStats {
  chainsScanned: number;
  chainsUpdated: number;
  chainsSkipped: number;
  totalMatches: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const GENERIC_FILENAMES = new Set([
  "package.json",
  "package-lock.json",
  "README.md",
  "readme.md",
  "CLAUDE.md",
  "claude.md",
  ".env",
  ".gitignore",
  ".gitconfig",
  "Makefile",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
]);

const QUALIFYING_TAG_PREFIXES = ["tool/", "domain/"]; // Expanded to match more tags
const MIN_SEGMENT_LEN = 2; // Lowered from 3
const MIN_FRAGMENT_LEN = 4; // Lowered from 8 - allow short but meaningful fragments like "mcp", "k8s", "rag"
const MIN_KEYWORD_LEN = 4; // Lowered from 6 - allow keywords like "mcp", "rag", "k8s"
const SCORE_THRESHOLD = 4; // Lowered from 8 - require weaker evidence
const MAX_MATCHES_PER_CHAIN = 15; // Increased from 10

const GENERIC_PATH_SEGMENTS = new Set([
  "src", "config", "configs", "scripts", "source", "plugins", "docs",
  "hooks", "manifests", "plans", "green", "blue", "router",
  "Documents", "OpenClaw-Vault", "opt-ai-agents",
]);

const MARKER_START = "<!-- auto-generated by vault-importer chain-linker \u2014 do not edit -->";
const MARKER_END = "<!-- end chain-linker -->";

const CODE_BEARING_EXTENSIONS = new Set([
  ".sh", ".bash", ".zsh",
  ".ts", ".js", ".mjs", ".cjs",
  ".py",
  ".yaml", ".yml",
  ".json",
  ".toml",
  ".lua",
  ".go", ".rs",
  ".css", ".html",
  ".sql",
  ".tf", ".nix",
  ".ini", ".conf",
  ".env",
]);

export function isCodeBearingFile(filename: string): boolean {
  const dot = filename.lastIndexOf(".");
  if (dot === -1) return false;
  return CODE_BEARING_EXTENSIONS.has(filename.slice(dot).toLowerCase());
}

// ---------------------------------------------------------------------------
// buildImportIndex
// ---------------------------------------------------------------------------

export function buildImportIndex(entries: ImportEntry[]): ImportIndex {
  const byFilename = new Map<string, ImportEntry[]>();
  const byPathSegment = new Map<string, ImportEntry[]>();
  const byTag = new Map<string, ImportEntry[]>();

  function addTo(map: Map<string, ImportEntry[]>, key: string, entry: ImportEntry) {
    const list = map.get(key) ?? [];
    list.push(entry);
    map.set(key, list);
  }

  for (const entry of entries) {
    addTo(byFilename, entry.sourceFile, entry);

    const pathParts = entry.sourcePath.split("/");
    const dirParts = pathParts.slice(0, -1);
    for (const seg of dirParts) {
      if (seg.length >= MIN_SEGMENT_LEN && !GENERIC_PATH_SEGMENTS.has(seg)) {
        addTo(byPathSegment, seg, entry);
      }
    }

    for (const tag of entry.tags) {
      if (QUALIFYING_TAG_PREFIXES.some(prefix => tag.startsWith(prefix))) {
        addTo(byTag, tag, entry);
      }
    }
  }

  return { byFilename, byPathSegment, byTag, all: [...entries] };
}

// ---------------------------------------------------------------------------
// parseImportNote
// ---------------------------------------------------------------------------

export function parseImportNote(content: string, notePath: string): ImportEntry | null {
  const fm = extractFrontmatter(content);
  if (!fm) return null;

  const title = fm["title"];
  if (!title) return null;

  const sourcePath = title;
  const sourceFile = basename(title);
  const displayName = title;
  const tags = parseTags(fm["tags"]);

  return { notePath, sourceFile, sourcePath, tags, displayName };
}

// ---------------------------------------------------------------------------
// scanImportNotes
// ---------------------------------------------------------------------------

export async function scanImportNotes(vaultRoot: string): Promise<ImportEntry[]> {
  // Scan multiple vault directories for content to link
  const directories = [
    "060-imports",
    "01-RESEARCH", 
    "020-concepts",
    "030-sources",
    "040-projects",
    "050-runtime",
    "070-tools",
  ];

  const entries: ImportEntry[] = [];

  for (const dir of directories) {
    const pattern = `${vaultRoot}/${dir}/**/*.md`;
    const files = await glob(pattern, { nodir: true, absolute: true });

    for (const absPath of files) {
      const notePath = absPath.replace(`${vaultRoot}/`, "");
      // Skip MOC files
      if (notePath.includes("MOC") || notePath.includes("index")) {
        continue;
      }

      let content: string;
      try {
        content = readFileSync(absPath, "utf-8");
      } catch {
        continue;
      }

      const entry = parseImportNote(content, notePath);
      if (entry) entries.push(entry);
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// parseChain
// ---------------------------------------------------------------------------

export function parseChain(content: string, path: string): ChainInfo | null {
  const fm = extractFrontmatter(content);
  if (!fm) return null;

  const handle = fm["handle"];
  if (!handle) return null;

  const tags = parseTags(fm["tags"]);
  // Strip frontmatter AND any existing auto-generated section before matching
  let bodyText = content.replace(/^---[\s\S]*?---\n*/m, "").trim();
  const markerStartEsc = MARKER_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const markerEndEsc = MARKER_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  bodyText = bodyText.replace(new RegExp(`${markerStartEsc}[\\s\\S]*?${markerEndEsc}`, "m"), "").trim();

  const wikilinkTargets: string[] = [];
  const wikilinkRe = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
  let match: RegExpExecArray | null;
  while ((match = wikilinkRe.exec(bodyText)) !== null) {
    wikilinkTargets.push(match[1].trim());
  }

  return { path, handle, tags, bodyText, wikilinkTargets };
}

// ---------------------------------------------------------------------------
// parseTargetNote
// ---------------------------------------------------------------------------

export function parseTargetNote(content: string, path: string): ChainInfo | null {
  const fm = extractFrontmatter(content);

  const handle = fm?.["handle"] || basename(path, ".md").replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();
  const tags = parseTags(fm?.["tags"]);

  let bodyText = content.replace(/^---[\s\S]*?---\n*/m, "").trim();
  const markerStartEsc = MARKER_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const markerEndEsc = MARKER_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  bodyText = bodyText.replace(new RegExp(`${markerStartEsc}[\\s\\S]*?${markerEndEsc}`, "m"), "").trim();

  if (bodyText.length < 50) return null;

  const wikilinkTargets: string[] = [];
  const wikilinkRe = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
  let match: RegExpExecArray | null;
  while ((match = wikilinkRe.exec(bodyText)) !== null) {
    wikilinkTargets.push(match[1].trim());
  }

  return { path, handle, tags, bodyText, wikilinkTargets };
}

// ---------------------------------------------------------------------------
// scoreMatches
// ---------------------------------------------------------------------------

export function scoreMatches(chain: ChainInfo, index: ImportIndex): ScoredMatch[] {
  const scoreMap = new Map<ImportEntry, { score: number; reasons: string[] }>();

  function add(entry: ImportEntry, points: number, reason: string) {
    const existing = scoreMap.get(entry) ?? { score: 0, reasons: [] };
    existing.score += points;
    existing.reasons.push(reason);
    scoreMap.set(entry, existing);
  }

  // 1. Exact filename match (+10), skip generics
  for (const [filename, entries] of index.byFilename) {
    if (GENERIC_FILENAMES.has(filename)) continue;
    const filenameEscaped = filename.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`(?<![\\w./])${filenameEscaped}(?![\\w])`, "i");
    if (re.test(chain.bodyText)) {
      for (const entry of entries) {
        add(entry, 10, `filename match: ${filename}`);
      }
    }
  }

  // 2. Repo wikilink match (+7)
  for (const target of chain.wikilinkTargets) {
    const repoMatch = target.match(/(?:repos\/)?([^/]+)$/);
    if (!repoMatch) continue;
    const repoName = repoMatch[1].toLowerCase();

    for (const entry of index.all) {
      const entryRepoSegment = entry.sourcePath.split("/")[0].toLowerCase();
      if (entryRepoSegment === repoName) {
        add(entry, 7, `repo wikilink: ${target} \u2192 ${repoName}`);
      }
    }
  }

  // 3. Path fragment in chain body (+5, segment >=8 chars, skip generics)
  for (const [segment, entries] of index.byPathSegment) {
    if (segment.length < MIN_FRAGMENT_LEN) continue;
    if (GENERIC_PATH_SEGMENTS.has(segment)) continue;
    const segEscaped = segment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`\\b${segEscaped}\\b`, "i");
    if (re.test(chain.bodyText)) {
      for (const entry of entries) {
        add(entry, 5, `path fragment: ${segment}`);
      }
    }
  }

  // 4. Handle keyword match (+4)
  const handleKeywords = chain.handle
    .toLowerCase()
    .split(/[_\s-]+/)
    .filter(w => w.length >= MIN_KEYWORD_LEN);

  for (const keyword of handleKeywords) {
    for (const entry of index.all) {
      const pathLower = entry.sourcePath.toLowerCase();
      if (pathLower.includes(keyword)) {
        add(entry, 4, `handle keyword: ${keyword}`);
      }
    }
  }

  // 5. Shared tag overlap (+3 per overlapping qualifying tag)
  const chainQualifyingTags = new Set(
    chain.tags.filter(t => QUALIFYING_TAG_PREFIXES.some(p => t.startsWith(p)))
  );

  for (const [tag, entries] of index.byTag) {
    if (chainQualifyingTags.has(tag)) {
      for (const entry of entries) {
        add(entry, 3, `shared tag: ${tag}`);
      }
    }
  }

  const results: ScoredMatch[] = [];
  for (const [entry, { score, reasons }] of scoreMap) {
    if (score >= SCORE_THRESHOLD) {
      results.push({ importEntry: entry, score, reasons });
    }
  }

  results.sort((a, b) => b.score - a.score || a.importEntry.notePath.localeCompare(b.importEntry.notePath));
  return results.slice(0, MAX_MATCHES_PER_CHAIN);
}

// ---------------------------------------------------------------------------
// injectAttachedFiles
// ---------------------------------------------------------------------------

export function injectAttachedFiles(
  chainContent: string,
  matches: ScoredMatch[],
  noteCache?: Map<string, string>
): string {
  if (matches.length === 0) return "";

  const sectionLines: string[] = [
    MARKER_START,
    "## Attached Files",
    "",
  ];

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    const linkPath = stripMd(m.importEntry.notePath);

    if (i === 0) {
      sectionLines.push(`![[${linkPath}]]`);
    } else {
      sectionLines.push(`- [[${linkPath}|${m.importEntry.displayName}]]`);
    }

    // Add inline code in <details> for code-bearing files when cache available
    if (noteCache && isCodeBearingFile(m.importEntry.sourceFile)) {
      const noteContent = noteCache.get(m.importEntry.notePath);
      if (noteContent) {
        const codeBlock = extractCodeBlock(noteContent);
        if (codeBlock) {
          const langLabel = codeBlock.language || "text";
          const displayFile = m.importEntry.sourceFile;
          sectionLines.push("");
          sectionLines.push(`<details><summary>📄 ${displayFile} (${langLabel}, ${codeBlock.lineCount} lines)</summary>`);
          sectionLines.push("");
          sectionLines.push(`\`\`\`${codeBlock.language}`);
          sectionLines.push(codeBlock.code);
          sectionLines.push("```");
          sectionLines.push("");
          sectionLines.push("</details>");
        }
      }
    }
  }

  sectionLines.push("");
  sectionLines.push(MARKER_END);
  const section = sectionLines.join("\n");

  // Idempotent: replace existing markers section
  const markerStartEscaped = MARKER_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const markerEndEscaped = MARKER_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const existingRe = new RegExp(
    `${markerStartEscaped}[\\s\\S]*?${markerEndEscaped}`,
    "m"
  );

  if (existingRe.test(chainContent)) {
    return chainContent.replace(existingRe, section);
  }

  // Insert before ## Triggers
  const triggersIdx = chainContent.search(/^## Triggers/m);
  if (triggersIdx !== -1) {
    return (
      chainContent.slice(0, triggersIdx) +
      section +
      "\n\n" +
      chainContent.slice(triggersIdx)
    );
  }

  // Append at end
  return chainContent.trimEnd() + "\n\n" + section;
}

// ---------------------------------------------------------------------------
// runChainLinker — scans chains, plans, and concepts; builds note cache
// ---------------------------------------------------------------------------

export async function runChainLinker(
  vaultRoot: string,
  dryRun = false,
  options?: { noCode?: boolean }
): Promise<ChainLinkerStats> {
  const stats: ChainLinkerStats = {
    chainsScanned: 0,
    chainsUpdated: 0,
    chainsSkipped: 0,
    totalMatches: 0,
  };

  const importEntries = await scanImportNotes(vaultRoot);
  const index = buildImportIndex(importEntries);

  // Build note content cache for code-bearing imports
  const noteCache = new Map<string, string>();
  if (!options?.noCode) {
    for (const entry of importEntries) {
      if (isCodeBearingFile(entry.sourceFile)) {
        try {
          const absPath = `${vaultRoot}/${entry.notePath}`;
          const content = readFileSync(absPath, "utf-8");
          noteCache.set(entry.notePath, content);
        } catch {
          // skip unreadable files
        }
      }
    }
    console.log(`Cached ${noteCache.size} code-bearing import notes`);
  }

  const targetPatterns: Array<{ pattern: string; parser: "chain" | "generic" }> = [
    { pattern: `${vaultRoot}/010-chains/chain.*.md`, parser: "chain" },
    { pattern: `${vaultRoot}/000-admin/plans/*.md`, parser: "generic" },
    { pattern: `${vaultRoot}/020-concepts/**/*.md`, parser: "generic" },
  ];

  let totalTokenEstimate = 0;

  for (const { pattern, parser } of targetPatterns) {
    const files = await glob(pattern, { nodir: true, absolute: true });

    for (const absPath of files) {
      stats.chainsScanned++;

      let content: string;
      try {
        content = readFileSync(absPath, "utf-8");
      } catch {
        stats.chainsSkipped++;
        continue;
      }

      const notePath = absPath.replace(`${vaultRoot}/`, "");

      // Skip MOC and index files
      if (notePath.includes("MOC") || notePath.includes("index/")) {
        stats.chainsSkipped++;
        continue;
      }

      const parsed = parser === "chain"
        ? parseChain(content, notePath)
        : parseTargetNote(content, notePath);

      if (!parsed) {
        stats.chainsSkipped++;
        continue;
      }

      const matches = scoreMatches(parsed, index);
      if (matches.length === 0) {
        stats.chainsSkipped++;
        continue;
      }

      const updated = injectAttachedFiles(
        content,
        matches,
        options?.noCode ? undefined : noteCache
      );
      if (!updated || updated === content) {
        stats.chainsSkipped++;
        continue;
      }

      stats.chainsUpdated++;
      stats.totalMatches += matches.length;

      const tokenEstimate = Math.round(updated.length / 4);
      totalTokenEstimate += tokenEstimate;

      if (!dryRun) {
        writeFileSync(absPath, updated, "utf-8");
      }

      const label = dryRun ? "[dry-run]" : "[updated]";
      console.log(`${label} ${notePath} \u2014 ${matches.length} attached, ~${tokenEstimate} tok`);
    }
  }

  console.log(`\nTotal estimated tokens across updated notes: ~${totalTokenEstimate}`);
  return stats;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function stripMd(notePath: string): string {
  return notePath.endsWith(".md") ? notePath.slice(0, -3) : notePath;
}

function extractFrontmatter(content: string): Record<string, string> | null {
  const match = content.match(/^---\n([\s\S]*?)\n---/m);
  if (!match) return null;

  const block = match[1];
  const result: Record<string, string> = {};
  const lines = block.split("\n");
  let currentKey: string | null = null;
  let arrayLines: string[] = [];
  let inArray = false;

  function flushArray() {
    if (currentKey && inArray) {
      result[currentKey] = arrayLines.join("\n");
    }
    inArray = false;
    arrayLines = [];
    currentKey = null;
  }

  for (const line of lines) {
    if (line.startsWith("  - ") || (line.startsWith("- ") && inArray)) {
      if (!inArray) inArray = true;
      arrayLines.push(line.trim().replace(/^-\s*/, ""));
    } else {
      const kvMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_-]*):\s*(.*)$/);
      if (kvMatch) {
        flushArray();
        const [, key, val] = kvMatch;
        const cleaned = val.trim().replace(/^["']|["']$/g, "");
        if (cleaned === "") {
          currentKey = key;
        } else {
          result[key] = cleaned;
        }
      } else if (line.trim() === "") {
        if (inArray) flushArray();
      }
    }
  }

  flushArray();
  return result;
}

function parseTags(raw: string | undefined): string[] {
  if (!raw) return [];
  return raw
    .split("\n")
    .map(l => l.trim().replace(/^-\s*/, ""))
    .filter(Boolean);
}
