import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { dirname } from "path";
import type { TransformResult } from "./transformer";

interface GroupedImports {
  [category: string]: TransformResult[];
}

export function generateImportsMoc(
  results: TransformResult[],
  vaultRoot: string
): void {
  const grouped: GroupedImports = {};

  for (const r of results) {
    const parts = r.destPath.split("/");
    const category = parts[1] ?? "uncategorized";
    if (!grouped[category]) grouped[category] = [];
    grouped[category].push(r);
  }

  const now = new Date().toISOString();
  const sections = Object.entries(grouped)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([category, files]) => {
      const fileLinks = files
        .sort((a, b) => a.destPath.localeCompare(b.destPath))
        .map((f) => {
          const noteName = f.destPath.replace(/\.md$/, "");
          return `- [[${noteName}]]`;
        })
        .join("\n");

      return `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n${fileLinks}`;
    })
    .join("\n\n");

  const moc = `---
title: IMPORTS MOC
tags:
  - type/moc
  - lifecycle/active
  - source/auto-generated
updated: ${now}
---

# IMPORTS MOC

> Auto-generated index of all imported files from the home directory.
> Updated automatically by vault-importer.

## Statistics

- **Total files**: ${results.length}
- **Categories**: ${Object.keys(grouped).length}
- **Last sync**: ${now}

## Imported Files

${sections}

---

## Backlinks

- [[DASHBOARD]] - Main navigation
- [[CONFIGS-MOC]] - Configuration files
- [[KNOWLEDGE-MOC]] - Knowledge chains
- [[COMMANDS-MOC]] - Commands and scripts

---

*Auto-generated by vault-importer. Do not edit manually.*
`;

  const mocPath = `${vaultRoot}/060-imports/IMPORTS-MOC.md`;
  const mocDir = dirname(mocPath);
  if (!existsSync(mocDir)) mkdirSync(mocDir, { recursive: true });
  writeFileSync(mocPath, moc, "utf-8");
}

export function writeImportedFile(
  result: TransformResult,
  vaultRoot: string,
  dryRun: boolean = false
): { action: "created" | "updated" | "skipped"; path: string } {
  const fullPath = `${vaultRoot}/${result.destPath}`;
  const dir = dirname(fullPath);

  if (existsSync(fullPath)) {
    const existing = readFileSync(fullPath, "utf-8");
    const checksumMatch = existing.match(/^checksum:\s*(\S+)$/m);
    if (checksumMatch && checksumMatch[1] === result.checksum) {
      return { action: "skipped", path: result.destPath };
    }

    if (!dryRun) {
      writeFileSync(fullPath, result.content, "utf-8");
    }
    return { action: "updated", path: result.destPath };
  }

  if (!dryRun) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(fullPath, result.content, "utf-8");
  }
  return { action: "created", path: result.destPath };
}
